### ISSUE TITLE
Expand description under heading "Use insightful visuals" on home page

### ISSUE THREAD

**Issue by rhoslynroebuck** [IRL2/nanover#12]
On the home page under the heading "Use insightful visuals", it says "Read the documentation on representations" and links to the Jupyter notebook about changing visualisations. 

It might be better to describe what the notebook does and then explicitly say that the link is to a Jupyter notebook. This should also include information about what packages are required to run the notebook.

**Comment by hjstroud** [comment]
This is no longer an issue after the re-design of the homepage
