### ISSUE TITLE
'nanover' heading in the Contents sidebar is unclear

### ISSUE THREAD

**Issue by rhoslynroebuck** [IRL2/nanover#16]
Is this automatically generated from the code base? If so, maybe it should go under another heading that is more explanatory of what it is. I think to a new reader this heading is confusing.

Maybe a paragraph explaining what the [nanover](https://irl2.github.io/nanover/python/modules.html) section is for

**Comment by hjstroud** [comment]
Based on our discussion, we propose changing this heading to `Modules`
