### ISSUE TITLE
IRL2 profile pic is not IRL logo

### ISSUE THREAD

**Issue by rhoslynroebuck** [IRL2/nanover#31]
You have to be an owner to change the profile picture of the organisation. @Ragzouken, would you be able to do this? None of us can because you need to be an owner. 

Here is the IRL logo: 
![FAVI-1](https://github.com/user-attachments/assets/52fbdd96-751a-4c36-9970-5b8f54205358)

**Comment by Ragzouken** [comment]
It's done (old one will be cached so you need to force refresh to see it)
